services:
  - type: web
    name: neurotypical-translator
    runtime: python
    buildCommand: |
      # Install system dependencies
      apt-get update -y
      apt-get install -y tesseract-ocr tesseract-ocr-eng libtesseract-dev
      # Create symlink to ensure consistent path
      ln -sf /usr/bin/tesseract /usr/local/bin/tesseract
      # Install Python requirements
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: TESSERACT_PATH
        value: /usr/local/bin/tesseract 