services:
  - type: web
    name: neurotypical-translator
    env: python
    buildCommand: |
      # Install system dependencies
      apt-get update -y
      apt-get install -y tesseract-ocr tesseract-ocr-eng
      # Verify installation and permissions
      which tesseract
      ls -l /usr/bin/tesseract
      # Install Python requirements
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: TESSERACT_PATH
        value: /usr/bin/tesseract 