services:
  - type: web
    name: neurotypical-translator
    env: docker
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVarsFile: .env 