services:
  - type: web
    name: neurotypical-translator
    runtime: docker
    buildCommand: docker build -t neurotypical-translator .
    startCommand: docker run -p $PORT:5000 neurotypical-translator
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    envVarsFile: .env 